# Generated by Django 5.0.1 on 2024-01-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flores', '0002_alter_floricultura_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome da flor')),
                ('quantidade', models.BigIntegerField(verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor unitário')),
            ],
            options={
                'verbose_name_plural': 'Flores',
            },
        ),
        migrations.DeleteModel(
            name='Floricultura',
        ),
    ]
